default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: postgres
  password: password

development:
  <<: *default
  database: receta_development

test:
  <<: *default
  database: receta_test

# production:
#   <<: *default
#   database: receta_production
#   username: receta
#   password: <%= ENV['RECETA_DATABASE_PASSWORD'] %>
